# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ca345da26310fc95d75f55cdffa27c6c06f823a07d4b0dd33fe81bdfba762320c16f9696439390d6ed929393c076d49df9a1192b13bf7c9706ebbd1626df5ec

test:
  secret_key_base: 75b5b06aa3eb35d46f6c017a4004f8337450a46e0f67f7a9f57745af3612f465542fced02c96d011bac1ce19d6a2da89e2e3da684fa7ec227845b98bc2e72027

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
